import React from "react";

export default function Contact({item}) {
  const {id, title, firstName, lastName, picture} = item

  String.prototype.toProperCase = function () {
    return this.replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();});
  };

  return (
    <div className="card">
      <div className="card-img">
        <img src={picture} alt={firstName} className="img" />
      </div>
      <div className="card-details">
        <h2 className="title">
          <span>{title.toProperCase()} </span>
          <span>{firstName.toProperCase()} </span>
          <span>{lastName.toProperCase()}</span>
        </h2>
      </div>
    </div>
  );
}

// model
/* 
{ id, title, firstName, lastName, picture }
{
    id: string(autogenerated)
    title: string("mr", "ms", "mrs", "miss", "dr", "")
    firstName: string(length: 2-50)
    lastName: string(length: 2-50)
    picture: string(url)    
} 
*/
